fail_fast: false
default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args:
        -   "--profile=black"
        -   "-m=3"  # multi_line_output
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args:
        -   "--line-length=88"
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        args:
        -   "--ignore=D100,D104,D203,D212"
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args:
        -   "--max-line-length=88"
        -   "--ignore=E203,W503"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args:
        -   "--ignore-missing-imports"
        -   "--follow-imports=silent"
        -   "--show-column-numbers"
        -   "--strict"
        -   "--allow-untyped-decorators"
        -   "--allow-subclassing-any"
        -   "--no-warn-unused-ignores"
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.0
    hooks:
    -   id: prettier
        files: \.[jt]sx?$
        args:
        -   "--config=./client/.prettierrc"
        -   "--write"
        -   "./client/src"
-   repo: https://github.com/eslint/eslint  # TODO(#12): remove "File ignored by default" warning
    rev: v7.32.0
    hooks:
    -   id: eslint
        files: \.[t]sx?$
        types: [file]
        verbose: true
        args:
        -    "--fix"
        -    "./client/src"
-   repo: https://github.com/EpicPi/ReqLockHook
    rev: v1.0.4
    hooks:
    -   id: req-lock
        files: server/Pip*
        verbose: true
        args:
        -   "--req server/Pipfile"
        -   "--lock server/Pipfile.lock"
-   repo: https://github.com/EpicPi/ReqLockHook
    rev: v1.0.4
    hooks:
    -   id: req-lock
        files: client/package*
        verbose: true
        args:
        -   "--req client/package.json"
        -   "--lock client/package-lock.json"
-   repo: https://github.com/EpicPi/ReqLockHook
    rev: v1.0.4
    hooks:
    -   id: req-lock
        files: "(Dockerfile|DEVBOX_VERSION)"
        verbose: true
        args:
        -   "--req Dockerfile"
        -   "--lock DEVBOX_VERSION"
