FROM python:3.8

EXPOSE 5000

# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIPENV_VENV_IN_PROJECT 1
ENV FLASK_APP 'server:app'
WORKDIR /home/worker/app/server/

# install pipenv
RUN pip install pipenv
ENV PATH /home/worker/app/server/.venv/bin:$PATH

ENTRYPOINT ["bash"]
