name: Backend CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  backendTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          cd server
          pip install pipenv
          pipenv shell
          pipenv install --dev

      - name: Run Backend Tests
        run: |
          cd server
          python -m pytest tests
