name: Backend CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  backendTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          cd server
          pip install pipenv
          pipenv install --dev

      - name: Run Backend Tests
        run: |
          cd server
          pipenv run pytest tests
