name: Backend CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_dispatch:

jobs:
  backendTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name:
        run: |
          bin/infra build
          touch dev.env
          bin/dev py-req
          bin/dev run pytest
# Our docker-compose.yml expects there to be a dev.env file. Since our testing environment doesn't actually
# need any of the secrets stored there, we can simply create an empty file: `touch dev.env`
