name: Backend CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  backendTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          cd server
          python -m pip install --upgrade pipenv wheel
          pipenv install --dev

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Run Backend Tests
        run: |
          cd server
          pipenv run pytest tests
