name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  migration-runner:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: run migration script
        env:
          MONGO_USER: ${{ secrets.MONGO_USER  }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD  }}
          MONGO_HOST: ${{ secrets.MONGO_HOST  }}
        run: |
          cd server
          pip install pipenv
          pipenv install --deploy
          pipenv run python3 -m src.db.runner

  backend-deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: migration-runner

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.EC2_HOSTNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/syncm8 &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            cd server &&
            source syncm8env/bin/activate &&
            pipenv install --deploy &&
            sudo systemctl restart syncm8.service
          '

  frontend-deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: backend-deploy

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Build React App
        run: |
          cd client
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Push to S3
        run: aws s3 sync ./client/build/ s3://syncm8.com --delete
