name: Frontend CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_dispatch:

jobs:
  frontendTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 10.x

      - name: Install Modules
        run: |
          cd client
          npm ci

      - name: Run Frontend Tests
        run: |
          cd client
          npm run test
