name: Frontend CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  eslintAndTests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Install modules
        run: |
          cd client
          npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Frontend Tests
        run: npm run test

