name: Heartbeat

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Cheack Heartbeat
        run : |
          RES=$(curl -s -o /dev/null -w "%{http_code}" https://backend.syncm8.com/test)
          GOOD_RES="200"
          if [ "$RES" == "$GOOD_RES" ];
            then echo 'Success';
            else exit 1;
          fi
          echo 'done'
