name: pre-commit

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/setup-node@v2
      with:
        node-version: 10.x

    - uses: pre-commit/action@v2.0.3
