name: pre-commit

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: actions/setup-node@v2
      with:
        node-version: 10.x
    - name: Install Modules
      run: |
        cd client
        npm ci

    - uses: pre-commit/action@v2.0.3
