name: pr-title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [ main, dev ]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest

    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        allowed_prefixes: '[feat],[fix],[migr],[chore]'
        prefix_case_sensitive: true
        max_length: 60
        github_token: ${{ github.token }}
